# GitHub Pages environment configuration
name: github-pages
url: https://940smiley.github.io/gitty-gitty-git-er
deployments_url: https://api.github.com/repos/940smiley/gitty-gitty-git-er/environments/github-pages/deployments
description: GitHub Pages environment for the Gitty-Gitty-Git-Er application
protected_branches: true
custom_branch_policies: false
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false

