name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies for client and server
      - name: Install dependencies
        run: |
          echo "Installing client dependencies..."
          cd client
          npm ci
          
          echo "Installing server dependencies..."
          cd ../server
          npm ci

      # Create production build environment file
      - name: Create .env file
        run: |
          cd client
          echo "VITE_API_URL=${{ secrets.API_URL || 'https://api.gitty-gitty-git-er.net' }}" > .env
          echo "VITE_GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}" >> .env
          echo "VITE_GITHUB_REDIRECT_URI=${{ secrets.GITHUB_REDIRECT_URI || '/.auth/login/github/callback' }}" >> .env
          echo "VITE_APP_NAME=Gitty-Gitty-Git-Er" >> .env
          echo "VITE_APP_VERSION=1.0.0" >> .env
          echo "VITE_ENABLE_OFFLINE_MODE=true" >> .env
          echo "VITE_ENABLE_NOTIFICATIONS=true" >> .env
          echo "VITE_ENABLE_PWA=true" >> .env
          echo "VITE_DEFAULT_THEME=light" >> .env
          echo "Created client .env file"
          cat .env

      # Deploy to Azure Static Web Apps
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # App location - the source code directory containing the client application
          app_location: "/"
          # API location - where the Azure Functions or API code lives
          api_location: "server"
          # Output location - the build output directory for the client application
          output_location: "client/dist"
          # App build command
          app_build_command: "npm run build"
          # API build command
          api_build_command: "npm run build"
          # Skip App build if API only changes
          skip_app_build: false
          # Skip API build if App only changes 
          skip_api_build: false
          # The build configuration for the API
          config_file_location: "/"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"

